services:
  php:
    # noinspection ComposeUnknownValues
    image: ghcr.io/phpyh/php:${PHP_IMAGE_VERSION:?Make sure `PHP_IMAGE_VERSION` is declared in `.env`}
    user: ${CONTAINER_USER:-}
    environment:
      INSIDE_DEVCONTAINER: true
      HISTFILE: /workspace/var/.docker_history
      COMPOSER_CACHE_DIR: /workspace/var/.composer_cache
    tty: true
    init: true
    volumes:
      - .:/workspace:cached
    working_dir: /workspace

  postgres:
    image: postgres:18.2-bookworm
    healthcheck:
      test: pg_isready -d phpyh -U phpyh
      interval: 5s
      timeout: 5s
      retries: 30
    environment:
      POSTGRES_USER: thesis
      POSTGRES_PASSWORD: thesis
    volumes:
      - postgres:/var/lib/postgresql:delegated
    ports:
      - '5432:5432'

volumes:
  postgres: ~
